easy_admin:
    entities:
         User:
             class: App\Entity\Access\User
             list:
               fields: ['id','name','username','email','enabled']

#        - App\Entity\Product
#        - App\Entity\Category
#        - App\Entity\User
